network:
  version: 2
  ethernets:
    eth0:
      optional: true
      dhcp4: true

  wifis:
    wlan0:
      optional: true
      dhcp4: true
      access-points:
        "Rostelecom-55":
          password: "876010659079"
        "ASUS":
          password: "485454qwer"
        "Ёжик":
          password: "apel_sin55"
        "CTT_wifi":
          password: "485454QwEr"
